version: '3.8'

networks:
  retailtech_network:
    name: retailtech_network
    driver: bridge

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - retailtech_network
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=https://frontend-agent-core.vercel.app
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_HEADERS=Content-Type,Authorization
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - retailtech_network
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data

volumes:
  evolution_instances:
  evolution_redis:
